### ISSUE TITLE
Check Prime Numbers 

### ISSUE THREAD

**Issue by Vivek-Py** [insidetheradar/LearnJava#1]
Write a program which checks if a number is prime or not in Java.

**Comment by reynaldo22** [comment]
let me do this
please assign me

**Comment by Vivek-Py** [comment]
Yeah sure!

**Comment by reynaldo22** [comment]
i write on new file with java
or just in documentation?

**Comment by ghost** [comment]
I have raised a PR. Please have a look if that is what is required.

**Comment by Vivek-Py** [comment]
@reynaldo22 Create a new file.

**Comment by Vivek-Py** [comment]
@rohanmarwaha222 I have addressed the issues. Check it out.

**Comment by ghost** [comment]
@insidetheradar I have added commits resolving the issue mentioned. Please review it.

**Comment by Somrajkarki** [comment]
can i do this too?

**Comment by Vivek-Py** [comment]
@Somrajkarki Yea sure

**Comment by Vivek-Py** [comment]
> @insidetheradar I have added commits resolving the issue mentioned. Please review it.

Merged it, Good job. Don't forget to star the repo for more tasks.
