### ISSUE TITLE
Armstrong Number

### ISSUE THREAD

**Issue by Vivek-Py** [insidetheradar/LearnJava#13]
Write a program to check if its Armstrong number or not in java. Also, Create a md file explaining the same.

**Comment by Somrajkarki** [comment]
can i do this?

**Comment by nchand** [comment]
@insidetheradar Please review PR

**Comment by ghost** [comment]
@insidetheradar I have raised PR for #12 and #13. Please review it.

**Comment by Vivek-Py** [comment]
> @insidetheradar Please review PR

Good Job!

**Comment by Vivek-Py** [comment]
> @insidetheradar I have raised PR for #12 and #13. Please review it.

Sure, I'll look into it

**Comment by himanshujaindev** [comment]
@insidetheradar can you assign this issue to me.. I can code the issue with an efficient algorithm

**Comment by Vivek-Py** [comment]
@himanshujain171  Go on, If you can code more efficiently.
