### ISSUE TITLE
Implement Insertion Sort

### ISSUE THREAD

**Issue by Vivek-Py** [insidetheradar/LearnJava#2]
Write a program to implement Insertion Sort in Java.

**Comment by leodalmacio** [comment]
Can I take this?

**Comment by insidetheradar** [comment]
@Yes, Go ahead.

**Comment by Vivek-Py** [comment]
@leodalmacio Yes, Sure!

**Comment by ghost** [comment]
Is anyone taking this up or should I take it up? Since I don't see any PR.

**Comment by ghost** [comment]
@insidetheradar I have implemented the insertion sort. Please review it.
