### ISSUE TITLE
Perform Depth First Search 

### ISSUE THREAD

**Issue by Vivek-Py** [insidetheradar/LearnJava#38]
Write the program to implement Depth First Search in Java.

**Comment by espoand** [comment]
hi, i can do this issue?

**Comment by Vivek-Py** [comment]
Sure, I'm assigning you for this @espoand

**Comment by Ayushi0508** [comment]
hi, i would like to do this issue

**Comment by NripeshKumar** [comment]
hi,can i  to do this issue?
